TK22WTPB-37 Video service
kraleppa/agh-tk pull request #29
Opened 2022-04-28 20:35 UTC by Gustaweek

2022-04-29 21:56 UTC, vojteq requested changes

2022-04-29 21:56 UTC, vojteq commented on video_service/src/emtpy.rs
> +
nie lepiej nazwac ten plik np main zeby bylo wiadomo gdzie startuje? to "empty" nic nie mowi :S

2022-04-29 21:56 UTC, vojteq commented on video_service/src/frame_extractor.rs
> +        return Err("Failed to get dir for extracted files".to_string());
te to_stringi na napisach to na pewno sa potrzebne?

2022-04-29 21:56 UTC, vojteq commented on video_service/src/frame_extractor.rs
> +        warn!("Failed to create dir for output files. Err: {:?}", dir_create_res.err());
chyba trzeba by wyjsc, skoro nie udalo sie stworzyc folderu?

2022-04-29 21:56 UTC, vojteq commented on video_service/src/frame_extractor.rs
> +            extracted_frame_count= extracted_frame_count+1;
troche ci sie formatowanie rozjezdza - raz bez spacji, raz z, a raz tak jak tu xd

2022-04-29 21:56 UTC, vojteq commented on video_service/src/main.rs
> +        return Ok(());
po pierwsze chyba nie powinno byc Ok() skoro jest blad XD
po drugie dobrze by bylo w petli ponawiac probe polaczenia i nie rzucac bledow, bo jak serwis bedzie tak w kolko rzucac blad i wstawac to mocno obciaza kompa :S

2022-04-29 21:56 UTC, vojteq commented on video_service/src/main.rs
> +    channel.queue_bind("format.movie", "format", "format.movie.*", Default::default())?;
mowilem ze za bindowanie bedziemy bic :V

2022-04-29 21:56 UTC, vojteq commented on video_service/src/main.rs
> +pub fn send_json_with_frames(channel: &Channel, files_with_frames: &Vector<String>, value: &Value) {
po co nagle publiczna funkcja

2022-04-29 21:56 UTC, vojteq commented on video_service/src/main.rs
> +mod extractor_test{
testu nie daloby sie wywalic do osobnego pliku?

2022-04-30 07:26 UTC, Gustaweek commented on video_service/src/emtpy.rs
> +
nie, bez tego pliku testy nie chcą się wykonać

2022-04-30 07:29 UTC, Gustaweek commented on video_service/src/frame_extractor.rs
> +        return Err("Failed to get dir for extracted files".to_string());
tak

2022-04-30 07:45 UTC, Gustaweek commented on video_service/src/main.rs
> +        return Ok(());
on tutaj wlasnie dzieki temu ze jest ok to ponawia probe tak długo jak w koncu sie uda polaczyc

2022-04-30 07:46 UTC, Gustaweek commented on video_service/src/main.rs
> +    channel.queue_bind("format.movie", "format", "format.movie.*", Default::default())?;
ajjjj mogles mowic wczesniej zapomnialem o tym a tak sie jebałem z tym...

2022-04-30 07:47 UTC, Gustaweek commented on video_service/src/main.rs
> +mod extractor_test{
no wlasnie jest problem bo jak był w osobnej (tak chcialem od poczatku) to albo testy sie nie wykonywały albo wywalało błedy... i nie potrafiłem tego naprawić

2022-04-30 07:47 UTC, Gustaweek commented on video_service/src/main.rs
> +pub fn send_json_with_frames(channel: &Channel, files_with_frames: &Vector<String>, value: &Value) {
a czemu nie ;)

2022-04-30 07:50 UTC, Gustaweek commented on video_service/src/main.rs
> +        return Ok(());
`[2022-04-30T07:42:28Z INFO  video_service] Prepering conncection

[2022-04-30T07:42:28Z INFO  video_service] Rabbit connection: amqp://admin:admin@rabbitmq:5672

Error: IoErrorWritingSocket { source: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" } }

[2022-04-30T07:42:30Z INFO  video_service] Prepering conncection

[2022-04-30T07:42:30Z INFO  video_service] Rabbit connection: amqp://admin:admin@rabbitmq:5672

Error: IoErrorWritingSocket { source: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" } }

[2022-04-30T07:42:33Z INFO  video_service] Prepering conncection

[2022-04-30T07:42:33Z INFO  video_service] Rabbit connection: amqp://admin:admin@rabbitmq:5672

Error: IoErrorWritingSocket { source: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" } }

[2022-04-30T07:42:35Z INFO  video_service] Prepering conncection

[2022-04-30T07:42:35Z INFO  video_service] Rabbit connection: amqp://admin:admin@rabbitmq:5672

[2022-04-30T07:42:35Z INFO  video_service] Consumer loop starting`

2022-04-30 20:01 UTC, vojteq requested changes

2022-04-30 20:01 UTC, vojteq commented on video_service/src/main.rs
> +        connection_res = Connection::insecure_open(&rabit_connection);
jeszcze jedna, ostatnia doczepka :S
w tym momencie laczysz sie, jak jest blad to laczysz sie znowu i dopiero czekasz 3s, moze lepiej zamienic kolejnoscia, bo jak w 27 nie uda ci sie polaczyc to tutaj prawdopodobnie tez

2022-05-01 12:54 UTC, vojteq approved these changes

2022-05-01 12:55 UTC, vojteq commented
blocked by changes in scraper (https://jira.lab.ii.agh.edu.pl/browse/TK22WTPB-49)

2022-05-02 10:05 UTC, vojteq requested changes

2022-05-02 10:05 UTC, vojteq commented on video_service/Dockerfile
> +RUN mkdir /data/output
zly katalog, podmien na taki jak w state serwisie

2022-05-03 11:02 UTC, vojteq requested changes

2022-05-03 11:02 UTC, vojteq commented on docker-compose.yaml
> +
dorzuc jeszcze ograniczenia pamieciowe jak w [tym commicie](https://github.com/kraleppa/agh-tk/commit/df2d3e725c56fee63bc9e534afc72fbf06824d92)

2022-05-08 15:40 UTC, Gustaweek commented
vojteq approved

2022-05-08 15:41 UTC, merged