TK22WTPB-39 Words typos microservice
kraleppa/agh-tk pull request #30
Opened 2022-04-29 07:52 UTC by jakeinrock

Words typos microservice.

2022-05-06 19:41 UTC, vojteq requested changes

2022-05-06 19:41 UTC, vojteq commented on docker-compose.yaml
>        - rabbitmq
ograniczenia pamieciowe

2022-05-06 19:41 UTC, vojteq commented on wordsTypos/Typos_receive_config.py
> +        self.passive = passive
do kosza

2022-05-06 19:41 UTC, vojteq commented on wordsTypos/Typos_receive_config.py
> +        self.durable = durable
do kosza

2022-05-06 19:41 UTC, vojteq commented on wordsTypos/Typos_receive_connect.py
> +                self._channel.queue_declare(queue=self.server.queue,
do kosza

2022-05-06 19:41 UTC, vojteq commented on wordsTypos/Typos_receive_connect.py
> +        message['words'] = typos
append

2022-05-06 19:41 UTC, vojteq commented on wordsTypos/Typos_send_config.py
> +        self.passive = passive
do kosza

2022-05-06 19:41 UTC, vojteq commented on wordsTypos/Typos_send_config.py
> +        self.exchange_type = exchange_type
do kosza

2022-05-06 19:41 UTC, vojteq commented on wordsTypos/Typos_send_config.py
> +        self.durable = durable
do kosza

2022-05-06 19:41 UTC, vojteq commented on wordsTypos/Typos_send_config.py
> +        self._channel.exchange_declare(
do kosza

2022-05-06 19:41 UTC, vojteq commented on wordsTypos/Typos_send_config.py
> +            passive=True,
do kosza

2022-05-06 19:41 UTC, vojteq commented on wordsTypos/Typos_send_config.py
> +            exchange_type='direct',
do kosza

2022-05-06 19:41 UTC, vojteq commented on wordsTypos/Typos_send_config.py
> +            durable=True,
do kosza

2022-05-06 19:41 UTC, vojteq commented on wordsTypos/Typos_send_connect.py
> +        self._channel.exchange_declare(
do kosza

2022-05-06 19:41 UTC, vojteq commented on wordsTypos/Typos_send_connect.py
> +            exchange_type='direct',
do kosza

2022-05-06 19:41 UTC, vojteq commented on wordsTypos/Typos_send_connect.py
> +            passive=True,
do kosza

2022-05-06 19:41 UTC, vojteq commented on wordsTypos/Typos_send_connect.py
> +            durable=True,
do kosza

2022-05-06 19:41 UTC, vojteq commented on wordsTypos/wordsTypos_run.py
> +        durable=True)
do kosza

2022-05-06 19:41 UTC, vojteq commented on wordsTypos/wordsTypos_run.py
> +        passive=True,
do kosza

2022-05-07 09:17 UTC, jakeinrock commented on wordsTypos/Typos_receive_config.py
> +        self.passive = passive
ok

2022-05-07 09:17 UTC, jakeinrock commented on wordsTypos/Typos_receive_config.py
> +        self.durable = durable
ok

2022-05-08 18:20 UTC, closed without merging