TK22WTPB-40 Words synonyms microservice
kraleppa/agh-tk pull request #31
Opened 2022-04-29 07:58 UTC by jakeinrock

Words synonyms microservice

2022-05-03 12:50 UTC, vojteq requested changes

2022-05-03 12:50 UTC, vojteq commented on wordsSynonyms/Synonyms_receive_connect.py
> +                        local_synonyms.append(dict_word[1:10])
moze wrzuc wszystkie synonimy, zamiast ograniczac sie maksymalnie do 9?

2022-05-03 12:50 UTC, vojteq commented on wordsSynonyms/Synonyms_receive_connect.py
> +        message['words'] = synonyms
nadpiszesz slowa znalezione przez inne serwisy

2022-05-03 12:50 UTC, vojteq commented on wordsSynonyms/Synonyms_send_config.py
> +        self._channel.exchange_declare(
nie musisz deklarowac exchange'a, on juz jest zadeklarowany i nic ten fragment tak na prawde nie wnosi, bo jesli by go z jakiegos powodu nie bylo to poleci blad i koniec programu

2022-05-03 12:50 UTC, vojteq commented on wordsSynonyms/Synonyms_send_connect.py
> +        self._channel.exchange_declare(
jak wyzej - wywalic

2022-05-03 12:50 UTC, vojteq commented on wordsSynonyms/wordsSynonyms_run.py
> +        passive=True,
nie powinno byc wgl potrzebne, bo nic nie powinienes deklarowac

2022-05-03 12:50 UTC, vojteq commented on wordsSynonyms/wordsSynonyms_run.py
> +        durable=True)
tak samo to

2022-05-05 10:47 UTC, jakeinrock commented on wordsSynonyms/Synonyms_receive_connect.py
> +                        local_synonyms.append(dict_word[1:10])
Zmienione

2022-05-05 10:47 UTC, jakeinrock commented on wordsSynonyms/Synonyms_receive_connect.py
> +        message['words'] = synonyms
Zmienione

2022-05-05 10:48 UTC, jakeinrock commented on wordsSynonyms/Synonyms_send_config.py
> +        self._channel.exchange_declare(
Nie wiem co tu się podziało, coś musiałem źle przerzucić, ale zmienione.

2022-05-05 10:48 UTC, jakeinrock commented on wordsSynonyms/Synonyms_send_connect.py
> +        self._channel.exchange_declare(
Zmienione

2022-05-05 10:49 UTC, jakeinrock commented on wordsSynonyms/wordsSynonyms_run.py
> +        passive=True,
Co do tego to niezbyt rozumiem. Jeżeli nie przekaże tych argumentów to nie utworze obiektu klasy RabbitMqServerConfigure (serverconfigure) do którego się potem sporo odnoszę.

2022-05-05 10:49 UTC, jakeinrock commented on wordsSynonyms/wordsSynonyms_run.py
> +        durable=True)
To samo co wyżej

2022-05-08 18:20 UTC, closed without merging